In [1]:
import numpy as np

In [2]:
np_a = np.array([1,2,3,4])

In [3]:
np_a

array([1, 2, 3, 4])

# Array 2 Dimensi

In [10]:
a = [[1,2,3], [4,5,22], [6,7,9]]

In [13]:
b = [[4,3,2], [1,2,4], [9,10,11]]

In [11]:
np_b = np.array(a)

In [12]:
np_b

array([[ 1,  2,  3],
       [ 4,  5, 22],
       [ 6,  7,  9]])

In [14]:
np_c = np.array(b)

In [15]:
np_c

array([[ 4,  3,  2],
       [ 1,  2,  4],
       [ 9, 10, 11]])

In [18]:
np_b + np_c

array([[ 5,  5,  5],
       [ 5,  7, 26],
       [15, 17, 20]])

In [19]:
np_b * np_c

array([[ 4,  6,  6],
       [ 4, 10, 88],
       [54, 70, 99]])

# Contoh Fungsi Numpy

In [20]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np_b * np.eye(3)

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

# Matrix

In [32]:
np_b

array([[ 1,  2,  3],
       [ 4,  5, 22],
       [ 6,  7,  9]])

In [27]:
np_b.shape

(3, 3)

In [28]:
np_b.ndim

2

In [30]:
np_b.size

9

In [31]:
np_b[0,0:2]

array([1, 2])

In [34]:
np_b.reshape(9,1) # Harus sama dengan np_b.size

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [22],
       [ 6],
       [ 7],
       [ 9]])

# Masking

In [35]:
ar = np.arange(1,101)
ar

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [37]:
ar % 2 == 0  # Conditional statement

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True])

In [40]:
ar[ar % 2 == 0]  # Masking

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

# Simple Calculation

In [49]:
np_b
A = np.ones([3,3])
B = np.eye(3)

In [43]:
np_b.sum(axis=0)  # Vertikal

array([11, 14, 34])

In [44]:
np_b.sum(axis=1)  # Horizontal

array([ 6, 31, 22])

In [45]:
dir(np_b)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [50]:
np.dot(np_b, A)  # Matriks np_b (3,3) Matriks A (3,3)

array([[ 6.,  6.,  6.],
       [31., 31., 31.],
       [22., 22., 22.]])